### ISSUE TITLE
Observable.subscribe_last

### ISSUE THREAD

**Issue by buckle2000** [bjornbytes/RxLua#14]
I wrote this to solve some "first come last serve" problems.
https://gist.github.com/buckle2000/0bc553e6aa9f3ae85b932b4a87ff07a1
You may add this to your sublime™ library.

**Comment by bjornbytes** [comment]
Thanks for sharing!  I think I'm going to close this for now because (as far as I can tell) it isn't part of RxJS.  Hopefully other people are able to find this useful though.  Happy to integrate it later on if others want this functionality added too.
