### ISSUE TITLE
CooperativeScheduler doesn't remove 'dead' thread when associated task errors.

### ISSUE THREAD

**Issue by greatwolf** [bjornbytes/RxLua#18]
Minimal test case for the behavior:

    local sched = require 'Rx'.CooperativeScheduler.create()

    sched:schedule(function()
      error 'first bail'
    end)

    repeat
      print( pcall(sched.update, sched) )
    until sched:isEmpty()

Is this the intended behavior?

If not, here's a proposed change that will properly remove the task from scheduler when it dies regardless of how it happened (eg. either from error or normal termination).

In [cooperativescheduler.lua:63](https://github.com/bjornbytes/RxLua/blob/master/src/schedulers/cooperativescheduler.lua#L63), modify to:

    if self.currentTime >= task.due then
      local success, delay = coroutine.resume(task.thread)

      if coroutine.status(task.thread) == 'dead' then
        table.remove(self.tasks, i)
      else
        task.due = math.max(task.due + (delay or 0), self.currentTime)
      end

      if not success then
        error(delay)
      end
    end

I can submit this as a PR too if needed.

**Comment by bjornbytes** [comment]
Yeah, that's definitely a bug.  Your fix looks good, feel free to submit a PR!
