### ISSUE TITLE
Operator :delay seems kind of wonky, especially when used with CooperativeScheduler

### ISSUE THREAD

**Issue by greatwolf** [bjornbytes/RxLua#20]
For instance:

    local Rx    = require 'rx'
    local scheduler = Rx.CooperativeScheduler.create()

    -- Cheer someone on using functional reactive programming
    local observable = Rx.Observable.of(2, 4, 6, 8, 10, "who do we appreciate")

    observable
      :delay(3000, scheduler)
      :map(function(value) return value .. '!' end)
      :subscribe(print, error, function() print "done" end)

    repeat
      scheduler:update(10)
    until scheduler:isEmpty()

This only gives the output:

    done

None of the numbers that's suppose to be emitted gets printed.

**Comment by bjornbytes** [comment]
The CooperativeScheduler was iterating in reverse order to make removal of tasks easier, which caused `onCompleted` to be called before any of the `onNext`s.  Fixed in https://github.com/bjornbytes/RxLua/commit/449e29b31cf37b202ae83f27182a63b680f075db.  Thanks!
