### ISSUE TITLE
Upload v0.0.3-1 to luarocks.org

### ISSUE THREAD

**Issue by ciarand** [bjornbytes/RxLua#26]
I see there's some rockspec configurations (including one for 0.0.3-1), but the only rxlua module I can find on luarocks.org is http://luarocks.org/modules/greatwolf/rxlua (which points to this project, but is missing v0.0.3-1).

Any chance of uploading the latest release there?

**Comment by xtofl** [comment]
@ciarand Do you know how to do that?  I'm willing to fork this repo and upload a version under 'my' user.

**Comment by bjornbytes** [comment]
Pinging @greatwolf since they uploaded the previous versions.

**Comment by bjornbytes** [comment]
0.0.3 is now uploaded to http://luarocks.org/modules/bjornbytes/rxlua.  I can't add it to the root manifest unfortunately since the name is taken, so you'll need to install it using `luarocks install bjornbytes/rxlua`.
